licenseKey: ""
mgmtClusterName: mgmt-cluster

glooMeshMgmtServer:
  enabled: true
  # image:
  #   pullPolicy: IfNotPresent
  #   registry: gcr.io/gloo-mesh
  #   repository: gloo-mesh-mgmt-server
  #   tag: 2.0.0-beta33
  ports:
    grpc: 9900
    healthcheck: 8090
    stats: 9091
  resources:
    requests:
      cpu: 125m
      memory: 256Mi
  serviceType: LoadBalancer

  # setting kubernetes service annotations
  # serviceOverrides:
  #   metadata:
  #     annotations:
  #       service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  #       service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  #       service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  #       service.beta.kubernetes.io/aws-load-balancer-subnets: my-subnet-1,my-subnet-2

  concurrency: 10
  relay:
    # Turn off token authentication and supply your own certificates
    disableCa: false
    # Do not generate a self signed root ca for relay (user will provide their own signing secret)
    disableCaCertGeneration: false
    # When doing token authentication but want to supply your own secret
    disableTokenGeneration: false
    pushRbac: true
    # Signing secret name generated by gloo mesh when using token authentication
    signingTlsSecret:
      name: relay-tls-signing-secret
    # mTLS secret used by gloo-mesh-mgmt-server for communication with agents
    tlsSecret:
      name: relay-server-tls-secret
    # Token based authentication secret used for agent authentication
    tokenSecret:
      key: token
      name: relay-identity-token-secret
      namespace: ""

# Gloo Mesh Dashboard
glooMeshUi:
  enabled: true
  # image:
    # pullPolicy: IfNotPresent
    # registry: gcr.io/gloo-mesh
    # repository: gloo-mesh-apiserver
    # tag: 2.0.0-beta33
  ports:
    console: 8090
    grpc: 10101
    healthcheck: 8081

  serviceType: ClusterIP
  # service annotations
  # serviceOverrides:
  #   metadata:
  #     annotations:
  #       service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  #       service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  #       service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  #       service.beta.kubernetes.io/aws-load-balancer-subnets: my-subnet-1,my-subnet-2

  # Gloo Mesh Dashboard Authentication
  auth:
    backend: ""
    enabled: false
    oidc:
      appUrl: ""
      clientId: ""
      clientSecret: ""
      clientSecretName: ""
      issuerUrl: ""
      session:
        backend: ""
        redis:
          host: ""

# the default prometheus install in gloo-mesh namespace
prometheus:
  enabled: true

# used as a cache for HA management plane 
glooMeshRedis:
  enabled: true