apiVersion: admin.gloo.solo.io/v2
kind: RateLimitServerSettings
metadata:
  name: rate-limit-server-settings
  namespace: backend-apis-team
spec:
  destinationServer:
    port:
      number: 8083
    ref:
      name: rate-limiter
      namespace: gloo-mesh-addons
      cluster: cluster1
---
apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitClientConfig
metadata:
  name: rate-limit-client-config
  namespace: backend-apis-team
spec:
  raw:
    rateLimits:
    - actions:
      - genericKey:
          descriptorValue: counter
---
apiVersion: admin.gloo.solo.io/v2
kind: RateLimitServerConfig
metadata:
  name: rate-limit-server-config
  namespace: backend-apis-team
spec:
  destinationServers:
  - ref:
      cluster: cluster1
      name: rate-limiter
      namespace: gloo-mesh-addons
    port:
      name: grpc
  raw:
    descriptors:
    - key: generic_key
      rateLimit:
        requestsPerUnit: 3
        unit: MINUTE
      value: counter
---
apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitPolicy
metadata:
  name: rate-limit-policy
  namespace: backend-apis-team
spec:
  applyToDestinations:
  - selector:
      labels:
        app: productcatalogservice
  config:
    serverSettings:
      name: rate-limit-server-settings
      namespace: backend-apis-team
      cluster: mgmt
    ratelimitClientConfig:
      name: rate-limit-client-config
      namespace: backend-apis-team
      cluster: mgmt
    ratelimitServerConfig:
      name: rate-limit-server-config
      namespace: backend-apis-team
      cluster: mgmt
    phase:
      preAuthz: { }