apiVersion: admin.gloo.solo.io/v2
kind: RateLimitServerSettings
metadata:
  name: product-catalog
  namespace: backend-apis-team
spec:
  destinationServer:
    port:
      number: 8083
    ref:
      name: rate-limiter
      namespace: gloo-mesh-addons
      cluster: cluster1
---
apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitClientConfig
metadata:
  name: product-catalog
  namespace: backend-apis-team
spec:
  raw:
    rateLimits:
    - actions:
      - genericKey:
          descriptorValue: counter
---
apiVersion: admin.gloo.solo.io/v2
kind: RateLimitServerConfig
metadata:
  name: product-catalog
  namespace: backend-apis-team
spec:
  destinationServers:
  - ref:
      cluster: cluster1
      name: rate-limiter
      namespace: gloo-mesh-addons
    port:
      name: grpc
  raw:
    descriptors:
    - key: generic_key
      rateLimit:
        requestsPerUnit: 2
        unit: MINUTE
      value: counter
---
apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitPolicy
metadata:
  name: product-catalog
  namespace: backend-apis-team
spec:
  applyToDestinations:
  - kind: VIRTUAL_DESTINATION
    selector:
      namespace: backend-apis-team
      name: product-catalog
  config:
    serverSettings:
      name: product-catalog
      namespace: backend-apis-team
      cluster: mgmt
    ratelimitClientConfig:
      name: product-catalog
      namespace: backend-apis-team
      cluster: mgmt
    ratelimitServerConfig:
      name: product-catalog
      namespace: backend-apis-team
      cluster: mgmt
    phase:
      postAuthz:
        priority: 3