cluster: mgmt
relay:
  serverAddress: gloo-mesh-mgmt-server.gloo-mesh.svc.cluster.local:9900
  authority: gloo-mesh-mgmt-server.gloo-mesh
  clientTlsSecret:
    name: gloo-agent-tls-cert
ext-auth-service:
  enabled: false
rate-limiter:
  enabled: false
glooMeshAgent:
  enabled: true