# use this if not setting licenseKey var
#licenseSecretName: gloo-mesh-license
global:
  cluster: mgmt
mgmtClusterName: mgmt
glooMeshMgmtServer:
  serviceType: LoadBalancer
  relay:
    disableCa: true                     # Disable mesh CA
    disableCaCertGeneration: true       # Don't generate CA certs
    disableTokenGeneration: true        # Don't generate tokens
    tlsSecret:
      name: gloo-server-tls-cert        # cert-manager creates this secret
  ports:
    healthcheck: 8091
glooMeshUi:
  serviceType: ClusterIP
  enabled: true
